//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from cprogram.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class cprogramLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, WS=8, ID=9, INT=10, 
		MUL=11, DIV=12, ADD=13, SUB=14, BWC=15, LNT=16;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "WS", "ID", "INT", 
		"MUL", "DIV", "ADD", "SUB", "BWC", "LNT"
	};


	public cprogramLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public cprogramLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'int'", "'('", "')'", "'{'", "'}'", "'return'", "';'", null, null, 
		null, "'*'", "'/'", "'+'", "'-'", "'~'", "'!'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, "WS", "ID", "INT", "MUL", 
		"DIV", "ADD", "SUB", "BWC", "LNT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "cprogram.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static cprogramLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,16,83,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,
		14,2,15,7,15,1,0,1,0,1,0,1,0,1,1,1,1,1,2,1,2,1,3,1,3,1,4,1,4,1,5,1,5,1,
		5,1,5,1,5,1,5,1,5,1,6,1,6,1,7,4,7,56,8,7,11,7,12,7,57,1,7,1,7,1,8,4,8,
		63,8,8,11,8,12,8,64,1,9,4,9,68,8,9,11,9,12,9,69,1,10,1,10,1,11,1,11,1,
		12,1,12,1,13,1,13,1,14,1,14,1,15,1,15,0,0,16,1,1,3,2,5,3,7,4,9,5,11,6,
		13,7,15,8,17,9,19,10,21,11,23,12,25,13,27,14,29,15,31,16,1,0,3,3,0,9,10,
		13,13,32,32,2,0,65,90,97,122,1,0,48,57,85,0,1,1,0,0,0,0,3,1,0,0,0,0,5,
		1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,
		0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,0,25,1,0,0,0,0,27,
		1,0,0,0,0,29,1,0,0,0,0,31,1,0,0,0,1,33,1,0,0,0,3,37,1,0,0,0,5,39,1,0,0,
		0,7,41,1,0,0,0,9,43,1,0,0,0,11,45,1,0,0,0,13,52,1,0,0,0,15,55,1,0,0,0,
		17,62,1,0,0,0,19,67,1,0,0,0,21,71,1,0,0,0,23,73,1,0,0,0,25,75,1,0,0,0,
		27,77,1,0,0,0,29,79,1,0,0,0,31,81,1,0,0,0,33,34,5,105,0,0,34,35,5,110,
		0,0,35,36,5,116,0,0,36,2,1,0,0,0,37,38,5,40,0,0,38,4,1,0,0,0,39,40,5,41,
		0,0,40,6,1,0,0,0,41,42,5,123,0,0,42,8,1,0,0,0,43,44,5,125,0,0,44,10,1,
		0,0,0,45,46,5,114,0,0,46,47,5,101,0,0,47,48,5,116,0,0,48,49,5,117,0,0,
		49,50,5,114,0,0,50,51,5,110,0,0,51,12,1,0,0,0,52,53,5,59,0,0,53,14,1,0,
		0,0,54,56,7,0,0,0,55,54,1,0,0,0,56,57,1,0,0,0,57,55,1,0,0,0,57,58,1,0,
		0,0,58,59,1,0,0,0,59,60,6,7,0,0,60,16,1,0,0,0,61,63,7,1,0,0,62,61,1,0,
		0,0,63,64,1,0,0,0,64,62,1,0,0,0,64,65,1,0,0,0,65,18,1,0,0,0,66,68,7,2,
		0,0,67,66,1,0,0,0,68,69,1,0,0,0,69,67,1,0,0,0,69,70,1,0,0,0,70,20,1,0,
		0,0,71,72,5,42,0,0,72,22,1,0,0,0,73,74,5,47,0,0,74,24,1,0,0,0,75,76,5,
		43,0,0,76,26,1,0,0,0,77,78,5,45,0,0,78,28,1,0,0,0,79,80,5,126,0,0,80,30,
		1,0,0,0,81,82,5,33,0,0,82,32,1,0,0,0,4,0,57,64,69,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
